site_name: Canwdev's Tech Blog - Obsidian

theme:
    name: 'material'
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 
  - mermaid2

extra_javascript:
  - javascripts/mathjax.js
#  - https://polyfill.io/v3/polyfill.min.js?features=es6
#  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#  - https://unpkg.com/mermaid/dist/mermaid.min.js 
